### ISSUE TITLE
2.2.3 Elevation considerations for distance along path with slope

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/doc-georeferencing-quick-guide#8]
Looking at the example of 2.2.3. Offset: distance along a road, I thought in this case, maybe common for countries with various elevation differences. When the distance on the road is given as in the example I show below, do I have to take the slope of the terrain into account to calculate the actual location of the coordinate based on the slope of the terrain? I couldn't find this consideration in the docs, if I missed it maybe you could point me out. Or maybe these considerations are not necessary.

![image](https://user-images.githubusercontent.com/15789737/97633838-b5f63380-1a02-11eb-8a76-8215792b9ffe.png)

**Comment by tucotuco** [comment]
This is a very astute observation @RicardoOrtizG . I think we should look for a worst-case scenario and see how much of a difference it can make. The best way to do this would be to draw a polyline along a path that changes altitude a lot in Google Earth Pro, once with the relief turned on and once without it and see what difference is makes. We could also think about a worst-case theoretical (geometry) scenario and see what difference it could make. For example, at what angle does the distance change by an appreciable percentage? What is appreciable? 1%? What is a reasonable limit for how steep a road can be? I think a river would not be a good example, because it is unlikely there would be a distance by river if the river isn't navigable (or walkable), and if it is navigable, it doesn't have any steep inclines.

**Comment by ArthurChapman** [comment]
Interesting.  Some roads have parts that are 12% and even up to 20%, but they twist and turn and the steepest parts are generally on a turn. I remember  from the Tour de France that some roads averaged 8-10% over 10-12 km or so.  In straight lines, the slopes could be even greater (i.e. not following a road). 

The more I think about this, the more complicated it gets.  Ricardo's example is just measuring the distance of a straight line where the beginning and end elevations are different. But if one was measuring by road there would be all sorts of ups and downs that may not show up when measuring on a map. 

In Google Earth's measuring tool you can draw a path and tick a box that says "Show Elevation Profile" It gives elevations, slopes at different places, elevation gain and loss, etc. I can't see if the distance is a linear distance or a terrain distance.  It appears to be the latter as the line follws the terrain.  However, wIth terrain turned off and using the line measure I got exactly the same distance as I did with Path and Terrain turned on showing elevation profile.  In doing some Google Searcths, the only information I could find was "Google does offer the caveat that the feature is not 100 percent accurate, particularly when measuring areas with 3D terrain"

![image](https://user-images.githubusercontent.com/22837459/99928829-f1d0ae80-2d9e-11eb-8f63-668ef8f98429.png)

**Comment by ArthurChapman** [comment]
Just found out from Google Earth Support that "Measurements don’t account for changes in elevation."

**Comment by tucotuco** [comment]
Hmm. So it would require a tool that could take the profile as input.

**Comment by ArthurChapman** [comment]
Perhaps this is something that needs to be considered for the next version(s). If one wanted to include for a straight line (by air) that someone may have measured off a map - one could do a basic calculation using the differences in elevation from start to finish using just c=sqrt( (lenth2+(elev-elev')2 ) without taking into consideration terrain changes.  Distance along a path, I would think, would more often be measured (by car, walking, by boat, etc.).  The basic method could still be way out if, for example the two points were on either side of a mountain or valley.  Do we need to just add some text (under a CARE warning perhaps).

**Comment by tucotuco** [comment]
I think we can actually deal with this in this release. There doesn't appear to be any easy way to estimate the real distance, but there are a couple of complicated ways and a simplified complicated way, so one has to really want this information to do these estimates. 
The first way is to make an image of the profile and export it to a tool that will let you distort the image so that the scale in x and y is the same (1m altitude = 1m horizontal distance), then measure along the path of elevation on the map.
The second way is to sum all the altitudinal gains between pair-wise minima and maxima and do the same for all the pair-wise altitudinal losses. Sum the gains and losses (both as positive, because the rises and falls both contribute to positive length gains). That sum serves as a scalar representation of all vector altitude changes. Use that sum as the rise (y) in a slope calculation where the run (x) is the horizontal length of the path. The estimated distance along the topography of the path is the sqrt(x^2+y^2).
The third, simplified complicated way is to do something similar to the second way, above, but use the (absolute value of the) net rise from the beginning elevation to the lowest elevation plus the (absolute value of the) net rise from the lowest elevation to the highest elevation plus the (absolute value of the) net rise from the highest elevation to the end elevation.
I think I can incorporate these issues and talk about the actual difference it makes under a variety of normal conditions.

**Comment by tucotuco** [comment]
There should also be mention of this in an elevation section in the GBP.

**Comment by ArthurChapman** [comment]
Do we need to do anything more in GBP. We have added a sentence, but we could make a link to QRG after you have written something.

**Comment by ArthurChapman** [comment]
We did add some wording in the GBP Section 3.4.2: "Note that measurements in Google Earth and Google Maps are direct lines and don't account for changes in elevation."

So, if you are writing something for the QRG @tucotuco we need to decide what to put in each document and where a link may work.  For example - if you do a detailed explanation of calculations in QRG we could add a link to that in the GBP.  Alternatively, for consistency, we could put an explanation in the GBP and just the calculations in QRG with a link back to GBP for the explanation.

**Comment by tucotuco** [comment]
Solution added in 235c85d29941374bb38474899e3b63b063402073 and https://github.com/gbif/doc-georeferencing-best-practices/commit/23e00b90b62834d829ec68692bc1b0b3c3282f63
